- name: Configure and Install Jenkins
  hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Upgrade all packages
    ansible.builtin.dnf:
      name: "*"
      state: latest

  - name: Install Prerequisite Packages
    ansible.builtin.dnf:
      name: 
        - java-11-openjdk
        - firewalld

  - name: Download Jenkins
    ansible.builtin.get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: Get Jenkins GPG Key
    ansible.builtin.rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key